const countriesFlag = [
  { name: "Albania", countryCode: "al" },
  { name: "Andorra", countryCode: "ad" },
  { name: "Austria", countryCode: "at" },
  { name: "Belarus", countryCode: "by" },
  { name: "Belgium", countryCode: "be" },
  { name: "Bosnia and Herzegovina", countryCode: "ba" },
  { name: "Bulgaria", countryCode: "bg" },
  { name: "Croatia", countryCode: "hr" },
  { name: "Cyprus", countryCode: "cy" },
  { name: "Czech Republic", countryCode: "cz" },
  { name: "Denmark", countryCode: "dk" },
  { name: "Estonia", countryCode: "ee" },
  { name: "Finland", countryCode: "fi" },
  { name: "France", countryCode: "fr" },
  { name: "Germany", countryCode: "de" },
  { name: "Greece", countryCode: "gr" },
  { name: "Hungary", countryCode: "hu" },
  { name: "Iceland", countryCode: "is" },
  { name: "Ireland", countryCode: "ie" },
  { name: "Italy", countryCode: "it" },
  { name: "Latvia", countryCode: "lv" },
  { name: "Liechtenstein", countryCode: "li" },
  { name: "Lithuania", countryCode: "lt" },
  { name: "Luxembourg", countryCode: "lu" },
  { name: "Malta", countryCode: "mt" },
  { name: "Moldova", countryCode: "md" },
  { name: "Monaco", countryCode: "mc" },
  { name: "Montenegro", countryCode: "me" },
  { name: "Netherlands", countryCode: "nl" },
  { name: "North Macedonia", countryCode: "mk" },
  { name: "Norway", countryCode: "no" },
  { name: "Poland", countryCode: "pl" },
  { name: "Portugal", countryCode: "pt" },
  { name: "Romania", countryCode: "ro" },
  { name: "Russia", countryCode: "ru" },
  { name: "San Marino", countryCode: "sm" },
  { name: "Serbia", countryCode: "rs" },
  { name: "Slovakia", countryCode: "sk" },
  { name: "Slovenia", countryCode: "si" },
  { name: "Spain", countryCode: "es" },
  { name: "Sweden", countryCode: "se" },
  { name: "Switzerland", countryCode: "ch" },
  { name: "Ukraine", countryCode: "ua" },
  { name: "United Kingdom", countryCode: "gb" },
  { name: "Vatican City", countryCode: "va" },
];

export default countriesFlag;
